language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
before_script:
  - pip install -r test_requirements.txt --use-mirrors
  - git clone git@github.com:z4r/python-coveralls-example.git
  - cd python-coveralls-example
  - py.test example/tests.py --cov=example
  - cd -
script:
  - py.test coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls